### ISSUE TITLE
Hi, I'm new to CoreML and really want to learn how to use it, can we talk about it?

### ISSUE THREAD

**Issue by stevendinggang** [xavierjd/News-Classifier#1]
Hi, I'm new to CoreML and really want to learn how to use it, can we talk about it?

**Comment by xavierjd** [comment]
Sure, do have previous experience in Machine Learning?

**Comment by xavierjd** [comment]
> Hi, I'm new to CoreML and really want to learn how to use it, can we talk about it?

Yes anytime, Do you have experience in SwiftUI?

**Comment by xavierjd** [comment]
> Hi, I'm new to CoreML and really want to learn how to use it, can we talk about it?
